server/config/routes.rb
PunchIn::Application.routes.draw do
  resources :punches
  root to: "punches#index"

end

server/app/models/punch.rb
class Punch < ActiveRecord::Base

	GEO_IP_TOOL = "http://geoiptool.com/en/?IP="

	COUNTRY_INDEX 		= 7
	CITY_INDEX 				= 13
	LONGITUDE_INDEX 	= 19
	LATITUDE_INDEX 		= 21
  
  attr_accessible :alias, :local_ip, :mac, :public_ip, 
  								:latitude, :longitude, :country, :city # APAGAR

  default_scope order: 'updated_at DESC'
	before_save :process_ip

	# validates_format_of :mac, with: /^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$/i
	# validates_format_of :public_ip, with: /^(?>(?>([a-f0-9]{1,4})(?>:(?1)){7}|(?!(?:.*[a-f0-9](?>:|$)){7,})((?1)(?>:(?1)){0,5})?::(?2)?)|(?>(?>(?1)(?>:(?1)){5}:|(?!(?:.*[a-f0-9]:){5,})(?3)?::(?>((?1)(?>:(?1)){0,3}):)?)?(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(?>\.(?4)){3}))$/i
	# validates_format_of :local_ip , with: /^(?>(?>([a-f0-9]{1,4})(?>:(?1)){7}|(?!(?:.*[a-f0-9](?>:|$)){7,})((?1)(?>:(?1)){0,5})?::(?2)?)|(?>(?>(?1)(?>:(?1)){5}:|(?!(?:.*[a-f0-9]:){5,})(?3)?::(?>((?1)(?>:(?1)){0,3}):)?)?(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])(?>\.(?4)){3}))$/i

	private

	def process_ip
		require 'open-uri'
		page = Nokogiri::HTML(open(GEO_IP_TOOL + public_ip))
		page.css('table.tbl_style tr td').each_with_index do |row,i|
			if i == COUNTRY_INDEX
				self.country = row.content
			elsif i == CITY_INDEX
				self.city = row.content
			elsif i == LONGITUDE_INDEX
				self.longitude = row.content.to_f
			elsif i == LATITUDE_INDEX
				self.latitude = row.content.to_f
			end
		end
	end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

server/app/controllers/punches_controller.rb
class PunchesController < ApplicationController

  # GET /punches
  # GET /punches.json
  def index
    @punches = Punch.all
    @query   = params[:search]

    if @query
      @query.downcase!
      punches_a = Punch.arel_table
      @punches = Punch.where(punches_a[:alias].matches("%#{@query}%").or(punches_a[:mac].matches("%#{@query}%")))
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @punches }
    end
  end

  # GET /punches/1
  # GET /punches/1.json
  def show
    @punch = Punch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @punch }
    end
  end

  # GET /punches/new
  # GET /punches/new.json
  def new
    @alias     = params[:alias] || ""
    @mac       = params[:mac]
    @local_ip  = params[:local_ip]
    @public_ip = params[:public_ip]

    if !@alias || !@mac || !@local_ip || !@public_ip
      @punch = Punch.new
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @punch }
      end
      return
    else
      logger.debug "find by mac"
      prev_punch = Punch.find_by_mac(@mac)
      if prev_punch
        prev_punch.update_attributes alias: @alias, local_ip: @local_ip, public_ip: @public_ip, mac: prev_punch.mac
        logger.debug "updated"
      else
        logger.debug "mac not found. will create"
        @punch = Punch.create alias: @alias, mac: @mac.downcase, local_ip: @local_ip, public_ip: @public_ip
        logger.debug "created"
      end
    end

    logger.debug "redirecting to root"
    redirect_to :root
  end

  # GET /punches/1/edit
  def edit
    @punch = Punch.find(params[:id])
  end

  # POST /punches
  # POST /punches.json
  def create
    @punch = Punch.new(params[:punch])

    respond_to do |format|
      if @punch.save
        format.html { redirect_to @punch, notice: 'Punch was successfully created.' }
        format.json { render json: @punch, status: :created, location: @punch }
      else
        format.html { render action: "new" }
        format.json { render json: @punch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /punches/1
  # PUT /punches/1.json
  def update
    @punch = Punch.find(params[:id])

    respond_to do |format|
      if @punch.update_attributes(params[:punch])
        format.html { redirect_to @punch, notice: 'Punch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @punch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /punches/1
  # DELETE /punches/1.json
  def destroy
    @punch = Punch.find(params[:id])
    @punch.destroy

    respond_to do |format|
      format.html { redirect_to punches_url }
      format.json { head :no_content }
    end
  end
end

server/app/helpers/application_helper.rb
module ApplicationHelper
end

server/app/helpers/punches_helper.rb
module PunchesHelper
end

server/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PunchIn</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="navbar">
    <h1 id="logo">Punch In</h1>
    <%= form_tag punches_path, method: "get" do %>
      <%= text_field_tag :search, @query %>
      <%= submit_tag "Search" %>
    <% end %>
</header>
<section id="body">
<%= yield %>
</section>

</body>
</html>

server/app/views/punches/_form.html.erb
<%= form_for(@punch) do |f| %>
  <% if @punch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@punch.errors.count, "error") %> prohibited this punch from being saved:</h2>

      <ul>
      <% @punch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :alias %><br />
    <%= f.text_field :alias %>
  </div>

  <div class="field">
    <%= f.label :mac %><br />
    <%= f.text_field :mac %>
  </div>
  <div class="field">
    <%= f.label :local_ip %><br />
    <%= f.text_field :local_ip %>
  </div>
  <div class="field">
    <%= f.label :public_ip %><br />
    <%= f.text_field :public_ip %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

server/app/views/punches/edit.html.erb
<h1>Editing punch</h1>

<%= render 'form' %>

<%= link_to 'Show', @punch %> |
<%= link_to 'Back', punches_path %>

server/app/views/punches/index.html.erb
<table>
  <tr>
    <th>Alias</th>
    <th>Mac</th>
    <th>Local ip</th>
    <th>Public ip</th>
    <th>Lat</th>
    <th>Lng</th>
    <th>Country</th>
    <th>City</th>
    <th>Updated at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @punches.each do |punch| %>
  <tr>
    <td><%= punch.alias %></td>
    <td><%= punch.mac %></td>
    <td><%= punch.local_ip %></td>
    <td><%= punch.public_ip %></td>
    <td><%= punch.latitude %></td>
    <td><%= punch.longitude %></td>
    <td><%= punch.country %></td>
    <td><%= punch.city %></td>
    <td><%= punch.updated_at %></td>

    <td><%= link_to 'Show', punch %></td>
    <td><%= link_to 'Edit', edit_punch_path(punch) %></td>
    <td><%= link_to 'Destroy', punch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Punch', new_punch_path %>

server/app/views/punches/new.html.erb
<h1>New punch</h1>

<%= render 'form' %>

<%= link_to 'Back', punches_path %>

server/app/views/punches/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Alias:</b>
  <%= @punch.alias %>
</p>

<p>
  <b>Mac:</b>
  <%= @punch.mac %>
</p>

<p>
  <b>Local ip:</b>
  <%= @punch.local_ip %>
</p>

<p>
  <b>Public ip:</b>
  <%= @punch.public_ip %>
</p>

<p>
  <b>Latitude:</b>
  <%= @punch.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @punch.longitude %>
</p>

<p>
  <b>Country:</b>
  <%= @punch.country %>
</p>

<p>
  <b>City:</b>
  <%= @punch.city %>
</p>


<%= link_to 'Edit', edit_punch_path(@punch) %> |
<%= link_to 'Back', punches_path %>